version: '3.8'
services:
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    networks:
      - mine
    environment:
      - VITE_API_URL= http://ficteer.com    
  
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      PYTHONPATH: /app
    depends_on:
      - db  
    networks:
      - mine   

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
    ports:
      - "5432:5432"
    networks:
      - mine   

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mine 

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    ports:
      - "8090:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt    
    networks:
      - mine      

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_params.conf:/etc/nginx/proxy_params.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - db
      - adminer
      - proxy

volumes:
  postgres_data:
  data:
  letsencrypt:

networks:
  mine:
    driver: bridge      
